"""Added alt_text to Photo model

Revision ID: 4f1b382f29f9
Revises: ebb82f1119fd
Create Date: 2025-02-15 21:57:13.314419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1b382f29f9'
down_revision = 'ebb82f1119fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_column('alt_text')

    # ### end Alembic commands ###
